name: derma_detect
description: "Projeto de detecção de doenças de pele"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_modular: 6.3.3
  flutter_bloc: ^8.1.2
  file_picker: ^6.2.0
  dio: ^5.4.3+1
  dartz: ^0.10.1
  collection: ^1.16.0
  auto_size_text: ^3.0.0
  bloc: ^8.0.1
  google_fonts: 6.1.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/google_fonts

flutter_native_splash:
  background_image: assets/images/bg_splash.png
