services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "5001:5001"
    env_file: .env # Carregar variáveis de ambiente do arquivo .env
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/derma-detect?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app # Montar o diretório atual para desenvolvimento local
      - /app/node_modules # Isolar o node_modules dentro do contêiner
    command: npm start
    expose:
      - "5001" # Expor a porta internamente para o Prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mongo-data:
    driver: local
  grafana-data:
    driver: local
