name: CI - DERMA CHECK

on:
  push:
    paths-ignore:
      - "*/.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: "stable"

      - name: Install dependencies - Main Project
        working-directory: client
        run: flutter pub get

      - name: Install dependencies in design system - Main Project
        working-directory: client/packages/design_system
        run: flutter pub get

      - name: Format Dart Code
        working-directory: client
        run: dart format --set-exit-if-changed --line-length 120 . || true

      - name: "Run Tests"
        working-directory: client
        run: flutter test --test-randomize-ordering-seed=random

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install JavaScript dependencies
        working-directory: backend
        run: npm install

      - name: "Run JavaScript Tests"
        working-directory: backend
        run: npm test
